name: Beta Release

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Beta Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      
      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build