name: Release

on:
  push:
    branches:
      - develop

  workflow_dispatch:
    inputs:
      release:
        description: 'Release Type'
        required: true
        default: 'None'
        type: choice
        options:
          - 'None'
          - 'Beta'
          - 'Latest'

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      
      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish Latest Release
        if: github.event.inputs.release == 'Latest'
        id: changesets
        uses: changesets/action@v1

      - name: Publish Beta Release
        if: steps.changesets.outputs.hasChangesets == 'true' || github.event.inputs.release == 'Beta'
        run: echo "Publishing Beta Release..."
