name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release Type'
        required: true
        default: 'None'
        type: choice
        options:
          - 'None'
          - 'Beta'
          - 'Latest'

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      
      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish Latest Release
        if: github.event.inputs.release == 'Beta'
        id: changesets
        uses: changesets/action@v1
        with:
          createGithubReleases: false
          version: yarn version:beta
          publish: yarn publish:beta
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: No Release
        run: echo "No Release Selected..."