name: 📦 Build & Release SerenityJS

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: 🚀 Changeset Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: 📦 Install Dependencies
        run: yarn install

      - name: 🏗️ Build
        run: yarn build

      - name: 📦 Create Release or Version PR
        id: changesets
        uses: changesets/action@v1
        with:
          createGithubReleases: true
          version: yarn run version
          publish: yarn run release
          setupGitUser: true
          commit: |
            Changeset: Increment package & dependency versions.

            Automated commit from `release` workflow.
          title: "chore(release): release packages"

      - name: 🧪 Create Beta Version (if not published)
        if: steps.changesets.outputs.published != 'true'
        run: |
          git checkout main
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          yarn run version:beta
          yarn run release:beta

  build-binaries:
    name: 🛠️ Build Release Binaries
    needs: release
    if: needs.release.outputs.published == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 🔧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: 🔧 Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 📦 Install Dependencies
        run: yarn

      - name: 🔧 Build
        run: yarn build

      - name: 🏗️ Bundle SerenityJS (Latest)
        run: yarn bundle:latest

      - name: 📤 Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: serenityjs-${{ matrix.os }}
          path: dist

  build-binaries-beta:
    name: 🧪 Build Beta Binaries
    needs: release
    if: needs.release.outputs.published != 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 🔧 Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 🔧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: 📦 Install Dependencies
        run: yarn

      - name: 🔧 Build
        run: yarn build

      - name: 🏗️ Bundle Serenity (Beta)
        run: yarn bundle:beta

      - name: 📤 Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: serenityjs-beta-${{ matrix.os }}
          path: dist
